### ISSUE TITLE
Youtube_load.php not grabbing CCing

### ISSUE THREAD

**Issue by tstefanich** [sosolimited/semantic_sabotage#74]
http://sabotage.sosolimited.com/?m=paragraph#

It seems the project is broken. I need to do some testing but I think its the regex for ttsurl. It seems not its not named ttsurl anymore but rather TTS_URL. I'm not super great at regex but I have forked it and if I can figure it out I will do a pull request.

**Comment by westhom** [comment]
@tstefanich Thanks for reporting! I've updated the regex.
